
services:

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@email.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "5050:80"
    networks:
      - example_network
  db:
    image: postgres:latest
    container_name: example_db
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: auth-example
    restart: always
    networks:
      - example_network
    ports:
      - "5432:5432"
    volumes:
      - example_data:/var/lib/postgresql/data
volumes:
  example_data:

networks:
  example_network:
